// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres_db

import (
	"time"

	"github.com/google/uuid"
)

type Action struct {
	ID          uuid.UUID
	Name        string
	Description string
	Type        string
	Config      map[string]string
}

type Alert struct {
	ID          uuid.UUID
	Fingerprint string
	Instance    string
	Status      string
	StartsAt    time.Time
	ReceivedAt  time.Time
	Labels      map[string]string
	Annotations map[string]string
}

type Rule struct {
	ID          uuid.UUID
	Name        string
	Description string
	Priority    int32
	Enabled     bool
}

type RuleCondition struct {
	ID       uuid.UUID
	RuleID   uuid.UUID
	Name     string
	Operator string
	Field    string
	Value    string
}
