// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres_db

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Alert struct {
	ID          pgtype.UUID
	Fingerprint string
	Instance    string
	Status      string
	StartsAt    time.Time
	ReceivedAt  time.Time
	Labels      map[string]string
	Annotations map[string]string
}
