// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package postgres_db

import (
	"context"
	"time"
)

const findAlertsByInstance = `-- name: FindAlertsByInstance :many
SELECT fingerprint, instance, status, starts_at, resolved_at, labels, annotations FROM alerts 
WHERE instance=$1
`

type FindAlertsByInstanceRow struct {
	Fingerprint string
	Instance    string
	Status      string
	StartsAt    time.Time
	ResolvedAt  time.Time
	Labels      map[string]string
	Annotations map[string]string
}

func (q *Queries) FindAlertsByInstance(ctx context.Context, instance string) ([]FindAlertsByInstanceRow, error) {
	rows, err := q.db.Query(ctx, findAlertsByInstance, instance)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindAlertsByInstanceRow
	for rows.Next() {
		var i FindAlertsByInstanceRow
		if err := rows.Scan(
			&i.Fingerprint,
			&i.Instance,
			&i.Status,
			&i.StartsAt,
			&i.ResolvedAt,
			&i.Labels,
			&i.Annotations,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertAlert = `-- name: InsertAlert :exec
INSERT INTO alerts (fingerprint, instance, status, starts_at, resolved_at, labels, annotations)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (fingerprint, status, starts_at) DO NOTHING
`

type InsertAlertParams struct {
	Fingerprint string
	Instance    string
	Status      string
	StartsAt    time.Time
	ResolvedAt  time.Time
	Labels      map[string]string
	Annotations map[string]string
}

func (q *Queries) InsertAlert(ctx context.Context, arg InsertAlertParams) error {
	_, err := q.db.Exec(ctx, insertAlert,
		arg.Fingerprint,
		arg.Instance,
		arg.Status,
		arg.StartsAt,
		arg.ResolvedAt,
		arg.Labels,
		arg.Annotations,
	)
	return err
}
