// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package postgres_db

import (
	"context"
	"time"
)

const insertAlert = `-- name: InsertAlert :exec
INSERT INTO alerts (fingerprint, status, starts_at, resolved_at, labels, annotations)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (fingerprint, status, starts_at) DO NOTHING
`

type InsertAlertParams struct {
	Fingerprint string
	Status      string
	StartsAt    time.Time
	ResolvedAt  time.Time
	Labels      map[string]string
	Annotations map[string]string
}

func (q *Queries) InsertAlert(ctx context.Context, arg InsertAlertParams) error {
	_, err := q.db.Exec(ctx, insertAlert,
		arg.Fingerprint,
		arg.Status,
		arg.StartsAt,
		arg.ResolvedAt,
		arg.Labels,
		arg.Annotations,
	)
	return err
}
