name: Main

on:
  push:

jobs:
  changes:
    runs-on: self-hosted
    container:
      image: reneruprecht/ci-node24
    outputs:
      backend: ${{ steps.filter.outputs.backend }}
      frontend: ${{ steps.filter.outputs.frontend }}
    steps:
    - uses: actions/checkout@v7

    - uses: dorny/paths-filter@v4
      id: filter
      with:
        filters: |
          backend:
            - 'backend/**'
          frontend:
            - 'frontend/**'
  backend:
    needs: changes
    if: needs.changes.outputs.backend == 'true'
    uses: ./.github/workflows/backend.yml

  frontend:
    needs: changes
    if: needs.changes.outputs.frontend == 'true'
    uses: ./.github/workflows/frontend.yml

  ci-success:
    needs: [changes, backend, frontend]
    runs-on: self-hosted
    container:
      image: reneruprecht/ci-node24
    if: always()
    steps:
      - name: Check required jobs
        run: |
          echo "CI completed"
